---
dist: xenial
language: python
python: 3.7
services:
  - docker

before_install:
  - bash tools/scripts/setup-env.sh

install:
  - pip install tox tox-travis pytest==4.5.0 PyYAML==5.1
  - curl https://github.com/AFCYBER-DREAM/piedpiper-midflayer/archive/master.zip -O /tmp/piedpiper-mindflayer.zip
  - unzip /tmp/piedpiper-mindflayer.zip

script: tox
